### ISSUE TITLE
error parsing multiple visual elements under a link

### ISSUE THREAD

**Issue by youngiif** [AdoHaha/modelrobot#11]
The URDF specification supports multiple visual elements under a single link element; however the following javascript error is thrown when parsing this scenario.

`TypeError: can't convert undefined to object`

I believe this is a new addition since this project was started, so should be an enhancement as opposed to a defect.

**Comment by AdoHaha** [comment]
hi, yes it seems to be a case. I will look at it, thanks.

**Comment by AdoHaha** [comment]
ok, done. Changes are visible in dev branch and on the mymodelrobot.appspot.com website

**Comment by youngiif** [comment]
That was quick.  Changes are working well.  Thanks a lot, this helps me a lot.

**Comment by AdoHaha** [comment]
If you do something cool using this tool, please share ;)
