### ISSUE TITLE
The demo at http://mymodelrobot.appspot.com/ isn't working

### ISSUE THREAD

**Issue by suemyinagaki** [AdoHaha/modelrobot#17]
I was using this demo to understand some URDF files but now it isn't working. Will the site be back up and running soon? Could you give me some instructions about how to run your code locally, please? I would be very grateful.

**Comment by AdoHaha** [comment]
hi, sorry for the delay, hopefully yes

**Comment by AdoHaha** [comment]
There was a billing issue, it is solved now
